performance:
  SpreadOperator:
    excludes:
      - "**/*Application.kt"
formatting:
  Indentation:
    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  NoWildcardImports:
    active: false
style:
  WildcardImport:
    active: false
complexity:
  LongParameterList:
    constructorThreshold: 8
    functionThreshold: 9
