performance:
  SpreadOperator:
    excludes:
      - "**/CellCaptureApplication.kt"
formatting:
  Indentation:
    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  NoWildcardImports:
    active: false
style:
  WildcardImport:
    active: false
complexity:
  TooManyFunctions:
    excludes:
      - "**/app/Config.kt"
      - "**/ComponentTest.kt"
      - "**/PartyTest.kt"
  LongParameterList:
    constructorThreshold: 8
    functionThreshold: 9
