performance:
  SpreadOperator:
    excludes:
      - "**/CellCaptureApplication.kt"
formatting:
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  NoWildcardImports:
    active: false
style:
  WildcardImport:
    active: false
